// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AuthLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AuthLoginResp struct {
	Token string   `json:"token"`
	User  UserInfo `json:"user"`
}

type DocumentInfo struct {
	ID        string `json:"id"`
	SubjectID string `json:"subject_id"`
	Filename  string `json:"filename"`
	FileType  string `json:"file_type"`
	FileSize  int64  `json:"file_size"`
	FileURL   string `json:"file_url"`
	Status    string `json:"status"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

type DocumentListReq struct {
	SubjectID string `json:"subject_id,optional"`
	Status    string `json:"status,optional"`
	Keyword   string `json:"keyword,optional"`
	Page      int    `json:"page,optional"`
	PageSize  int    `json:"page_size,optional"`
}

type DocumentListResp struct {
	List  []DocumentInfo `json:"list"`
	Total int64          `json:"total"`
}

type DocumentUploadResp struct {
	Document DocumentInfo `json:"document"`
}

type RetrievalChunk struct {
	ID         string  `json:"id"`
	DocID      string  `json:"doc_id"`
	DocName    string  `json:"doc_name"`
	SubjectID  string  `json:"subject_id"`
	UserID     string  `json:"user_id"`
	ChunkIndex int64   `json:"chunk_index"`
	Page       int64   `json:"page"`
	Section    string  `json:"section"`
	Content    string  `json:"content"`
	Score      float64 `json:"score"`
}

type RetrievalSearchReq struct {
	SubjectID string `json:"subject_id"`
	Query     string `json:"query"`
	TopK      int    `json:"top_k,optional"`
}

type RetrievalSearchResp struct {
	List []RetrievalChunk `json:"list"`
}

type SubjectCreateReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Visibility  string `json:"visibility,optional"`
}

type SubjectCreateResp struct {
	Subject SubjectInfo `json:"subject"`
}

type SubjectDeleteReq struct {
	ID string `json:"id"`
}

type SubjectDeleteResp struct {
	Deleted bool `json:"deleted"`
}

type SubjectDetailReq struct {
	ID string `json:"id"`
}

type SubjectDetailResp struct {
	Subject SubjectInfo `json:"subject"`
}

type SubjectInfo struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Visibility  string `json:"visibility"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type SubjectListReq struct {
	Keyword  string `json:"keyword,optional"`
	Page     int    `json:"page,optional"`
	PageSize int    `json:"page_size,optional"`
}

type SubjectListResp struct {
	List  []SubjectInfo `json:"list"`
	Total int64         `json:"total"`
}

type SubjectUpdateReq struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Visibility  string `json:"visibility,optional"`
}

type SubjectUpdateResp struct {
	Subject SubjectInfo `json:"subject"`
}

type UserInfo struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

type UserMeResp struct {
	User UserInfo `json:"user"`
}
