// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AdminLogClearReq struct {
	SubjectID string `json:"subject_id,optional"`
}

type AdminLogClearResp struct {
	Cleared int64 `json:"cleared"`
}

type AdminLogListReq struct {
	SubjectID string `json:"subject_id,optional"`
	Status    string `json:"status,optional"`
	Page      int    `json:"page,optional"`
	PageSize  int    `json:"page_size,optional"`
}

type AdminLogListResp struct {
	List  []ParseLogInfo `json:"list"`
	Total int64          `json:"total"`
}

type AdminSummaryResp struct {
	SubjectTotal     int64 `json:"subject_total"`
	DocumentTotal    int64 `json:"document_total"`
	ChunkTotal       int64 `json:"chunk_total"`
	SessionTotal     int64 `json:"session_total"`
	IndexedTotal     int64 `json:"indexed_total"`
	ProcessingTotal  int64 `json:"processing_total"`
	FailedTotal      int64 `json:"failed_total"`
	PendingTaskTotal int64 `json:"pending_task_total"`
	RunningTaskTotal int64 `json:"running_task_total"`
	FailedTaskTotal  int64 `json:"failed_task_total"`
}

type AdminTaskClearResp struct {
	Cleared int64 `json:"cleared"`
}

type AdminTaskListReq struct {
	SubjectID string `json:"subject_id,optional"`
	Status    string `json:"status,optional"`
	TaskType  string `json:"task_type,optional"`
	Page      int    `json:"page,optional"`
	PageSize  int    `json:"page_size,optional"`
}

type AdminTaskListResp struct {
	List  []IndexTaskInfo `json:"list"`
	Total int64           `json:"total"`
}

type AgentStep struct {
	ID         string `json:"id"`
	Kind       string `json:"kind"`
	Title      string `json:"title"`
	Tool       string `json:"tool"`
	State      string `json:"state"`
	Iteration  int    `json:"iteration"`
	Status     string `json:"status"`
	Detail     string `json:"detail"`
	DurationMS int64  `json:"duration_ms"`
}

type AuthLoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type AuthLoginResp struct {
	Token string   `json:"token"`
	User  UserInfo `json:"user"`
}

type AuthRegisterReq struct {
	Username        string `json:"username"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
	Nickname        string `json:"nickname,optional"`
	Email           string `json:"email,optional"`
}

type ChatAskReq struct {
	SessionID        string   `json:"session_id,optional"`
	MessageID        string   `json:"message_id,optional"`
	SubjectID        string   `json:"subject_id"`
	Query            string   `json:"query"`
	TopK             int      `json:"top_k,optional"`
	LlmProvider      string   `json:"llm_provider,optional"`
	LlmModel         string   `json:"llm_model,optional"`
	WebSearch        bool     `json:"web_search,optional"`
	ExpectedDocIDs   []string `json:"expected_doc_ids,optional"`
	ExpectedChunkIDs []string `json:"expected_chunk_ids,optional"`
	ExpectedRoute    string   `json:"expected_route,optional"`
	ExpectedOutcome  string   `json:"expected_outcome,optional"`
}

type ChatAskResp struct {
	RunID         string           `json:"run_id"`
	Answer        string           `json:"answer"`
	Chunks        []RetrievalChunk `json:"chunks"`
	ExternalLinks []ExternalLink   `json:"external_links"`
	Metrics       RetrievalMetrics `json:"metrics"`
	AgentSteps    []AgentStep      `json:"agent_steps"`
}

type ChatRunReq struct {
	RunID string `json:"run_id"`
}

type ChatRunEventsReq struct {
	RunID         string `json:"run_id"`
	AfterSequence int64  `json:"after_sequence,optional"`
	Limit         int    `json:"limit,optional"`
}

type ChatRunInfo struct {
	ID              string `json:"id"`
	Status          string `json:"status"`
	SubjectID       string `json:"subject_id"`
	SessionID       string `json:"session_id"`
	MessageID       string `json:"message_id"`
	ErrorMessage    string `json:"error_message"`
	CancelRequested bool   `json:"cancel_requested"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type ChatRunEventInfo struct {
	Sequence  int64          `json:"sequence"`
	Type      string         `json:"type"`
	Payload   map[string]any `json:"payload"`
	CreatedAt string         `json:"created_at"`
}

type ChatRunDetailResp struct {
	Run    ChatRunInfo    `json:"run"`
	Result map[string]any `json:"result"`
}

type ChatRunEventsResp struct {
	List []ChatRunEventInfo `json:"list"`
}

type ChatRunCancelResp struct {
	Cancelled bool `json:"cancelled"`
}

type ChatMessageInfo struct {
	ID            string           `json:"id"`
	Question      string           `json:"question"`
	Answer        string           `json:"answer"`
	Chunks        []RetrievalChunk `json:"chunks"`
	ExternalLinks []ExternalLink   `json:"external_links"`
	Metrics       RetrievalMetrics `json:"metrics"`
	ModelLabel    string           `json:"model_label"`
	ModelID       string           `json:"model_id"`
	WebSearch     bool             `json:"web_search"`
	AgentSteps    []AgentStep      `json:"agent_steps"`
	CreatedAt     string           `json:"created_at"`
}

type ChatSessionCreateReq struct {
	ID          string `json:"id"`
	SubjectID   string `json:"subject_id,optional"`
	Title       string `json:"title"`
	LlmProvider string `json:"llm_provider,optional"`
	LlmModel    string `json:"llm_model,optional"`
}

type ChatSessionCreateResp struct {
	Session ChatSessionInfo `json:"session"`
}

type ChatSessionDeleteReq struct {
	ID string `json:"id"`
}

type ChatSessionDeleteResp struct {
	Deleted bool `json:"deleted"`
}

type ChatSessionInfo struct {
	ID          string            `json:"id"`
	Title       string            `json:"title"`
	SubjectID   string            `json:"subject_id"`
	LlmProvider string            `json:"llm_provider"`
	LlmModel    string            `json:"llm_model"`
	CreatedAt   string            `json:"created_at"`
	UpdatedAt   string            `json:"updated_at"`
	Messages    []ChatMessageInfo `json:"messages"`
}

type ChatSessionListResp struct {
	List []ChatSessionInfo `json:"list"`
}

type ChatSessionUpdateReq struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

type ChatSessionUpdateResp struct {
	Updated bool `json:"updated"`
}

type DocumentChunkInfo struct {
	ID         string `json:"id"`
	ChunkIndex int    `json:"chunk_index"`
	Page       int    `json:"page"`
	Section    string `json:"section"`
	Content    string `json:"content"`
	TokenCount int    `json:"token_count"`
}

type DocumentClearFailedResp struct {
	Deleted int64 `json:"deleted"`
}

type DocumentDeleteReq struct {
	ID string `json:"id"`
}

type DocumentDeleteResp struct {
	Task IndexTaskInfo `json:"task"`
}

type DocumentDetailReq struct {
	ID string `json:"id"`
}

type DocumentDetailResp struct {
	Document DocumentInfo        `json:"document"`
	Chunks   []DocumentChunkInfo `json:"chunks"`
	Tasks    []IndexTaskInfo     `json:"tasks"`
	Logs     []ParseLogInfo      `json:"logs"`
}

type DocumentInfo struct {
	ID           string `json:"id"`
	SubjectID    string `json:"subject_id"`
	Filename     string `json:"filename"`
	FileType     string `json:"file_type"`
	FileSize     int64  `json:"file_size"`
	FileURL      string `json:"file_url"`
	Status       string `json:"status"`
	ErrorMessage string `json:"error_message"`
	Progress     int    `json:"progress"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type DocumentListReq struct {
	SubjectID string `json:"subject_id,optional"`
	Status    string `json:"status,optional"`
	Keyword   string `json:"keyword,optional"`
	Page      int    `json:"page,optional"`
	PageSize  int    `json:"page_size,optional"`
}

type DocumentListResp struct {
	List  []DocumentInfo `json:"list"`
	Total int64          `json:"total"`
}

type DocumentUploadResp struct {
	Document DocumentInfo `json:"document"`
}

type ExternalLink struct {
	Title   string `json:"title"`
	URL     string `json:"url"`
	Snippet string `json:"snippet"`
}

type IndexTaskInfo struct {
	ID           string `json:"id"`
	DocID        string `json:"doc_id"`
	SubjectID    string `json:"subject_id"`
	Filename     string `json:"filename"`
	TaskType     string `json:"task_type"`
	Status       string `json:"status"`
	RetryCount   int    `json:"retry_count"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
	UpdatedAt    string `json:"updated_at"`
}

type IndexTaskRetryReq struct {
	ID string `json:"id"`
}

type IndexTaskRetryResp struct {
	Task IndexTaskInfo `json:"task"`
}

type ModelServiceSettingsResp struct {
	Provider            string `json:"provider"`
	BaseURL             string `json:"base_url"`
	EmbeddingModel      string `json:"embedding_model"`
	EmbeddingDimension  int    `json:"embedding_dimension"`
	APIKeyConfigured    bool   `json:"api_key_configured"`
	APIKeyHint          string `json:"api_key_hint"`
	ConfigurationSource string `json:"configuration_source"`
}

type ModelServiceSettingsUpdateReq struct {
	APIKey string `json:"api_key"`
}

type ParseLogInfo struct {
	ID           string `json:"id"`
	DocID        string `json:"doc_id"`
	Filename     string `json:"filename"`
	Status       string `json:"status"`
	Message      string `json:"message"`
	ErrorMessage string `json:"error_message"`
	CreatedAt    string `json:"created_at"`
}

type RetrievalChunk struct {
	ID              string  `json:"id"`
	EvidenceID      string  `json:"evidence_id"`
	TenantID        string  `json:"tenant_id"`
	DocID           string  `json:"doc_id"`
	DocName         string  `json:"doc_name"`
	SubjectID       string  `json:"subject_id"`
	UserID          string  `json:"user_id"`
	ChunkIndex      int64   `json:"chunk_index"`
	Page            int64   `json:"page"`
	Section         string  `json:"section"`
	Content         string  `json:"content"`
	DocumentVersion int     `json:"document_version"`
	ContentHash     string  `json:"content_hash"`
	Score           float64 `json:"score"`
	RawScore        float64 `json:"raw_score"`
	Source          string  `json:"source"`
}

type RetrievalMetrics struct {
	OriginalQuery    string  `json:"original_query"`
	SearchQuery      string  `json:"search_query"`
	QueryRewritten   bool    `json:"query_rewritten"`
	Reranked         bool    `json:"reranked"`
	TopK             int     `json:"top_k"`
	CandidateCount   int     `json:"candidate_count"`
	ReturnedCount    int     `json:"returned_count"`
	SubQueryCount    int     `json:"sub_query_count"`
	ExpectedCount    int     `json:"expected_count"`
	RecallHitCount   int     `json:"recall_hit_count"`
	RecallAtK        float64 `json:"recall_at_k"`
	Route            string  `json:"route"`
	RouteCorrect     bool    `json:"route_correct"`
	LatencyMS        int64   `json:"latency_ms"`
	EvaluationPassed bool    `json:"evaluation_passed"`
	CitationCount    int     `json:"citation_count"`
	Answered         bool    `json:"answered"`
	OutcomeCorrect   bool    `json:"outcome_correct"`
}

type RetrievalSearchReq struct {
	SubjectID        string   `json:"subject_id"`
	Query            string   `json:"query"`
	TopK             int      `json:"top_k,optional"`
	ExpectedDocIDs   []string `json:"expected_doc_ids,optional"`
	ExpectedChunkIDs []string `json:"expected_chunk_ids,optional"`
	ExpectedRoute    string   `json:"expected_route,optional"`
}

type RetrievalSearchResp struct {
	List    []RetrievalChunk `json:"list"`
	Metrics RetrievalMetrics `json:"metrics"`
}

type SubjectCreateReq struct {
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Visibility  string `json:"visibility,optional"`
}

type SubjectCreateResp struct {
	Subject SubjectInfo `json:"subject"`
}

type SubjectDeleteReq struct {
	ID string `json:"id"`
}

type SubjectDeleteResp struct {
	Deleted bool `json:"deleted"`
}

type SubjectDetailReq struct {
	ID string `json:"id"`
}

type SubjectDetailResp struct {
	Subject SubjectInfo `json:"subject"`
}

type SubjectInfo struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Visibility  string `json:"visibility"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

type SubjectListReq struct {
	Keyword  string `json:"keyword,optional"`
	Page     int    `json:"page,optional"`
	PageSize int    `json:"page_size,optional"`
}

type SubjectListResp struct {
	List  []SubjectInfo `json:"list"`
	Total int64         `json:"total"`
}

type SubjectUpdateReq struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description,optional"`
	Visibility  string `json:"visibility,optional"`
}

type SubjectUpdateResp struct {
	Subject SubjectInfo `json:"subject"`
}

type UserInfo struct {
	ID       string `json:"id"`
	TenantID string `json:"tenant_id"`
	Username string `json:"username"`
	Nickname string `json:"nickname"`
	Email    string `json:"email"`
	Language string `json:"language"`
}

type UserMeResp struct {
	User UserInfo `json:"user"`
}

type UserPasswordUpdateReq struct {
	OldPassword     string `json:"old_password"`
	NewPassword     string `json:"new_password"`
	ConfirmPassword string `json:"confirm_password"`
}

type UserPasswordUpdateResp struct {
}

type UserUpdateReq struct {
	Nickname string `json:"nickname,optional"`
	Email    string `json:"email,optional"`
	Language string `json:"language"`
}

type UserUpdateResp struct {
	User UserInfo `json:"user"`
}
