// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "enterprise-rag/backend/internal/handler/auth"
	document "enterprise-rag/backend/internal/handler/document"
	retrieval "enterprise-rag/backend/internal/handler/retrieval"
	subject "enterprise-rag/backend/internal/handler/subject"
	"enterprise-rag/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	authMiddleware := serverCtx.AuthMiddleware.Handle

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/login",
				Handler: auth.AuthLoginHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares([]rest.Middleware{authMiddleware},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/users/me",
				Handler: auth.UserMeHandler(serverCtx),
			},
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares([]rest.Middleware{authMiddleware},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/documents/list",
				Handler: document.DocumentListHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/documents/upload",
				Handler: document.DocumentUploadHandler(serverCtx),
			},
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares([]rest.Middleware{authMiddleware},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/retrieval/search",
				Handler: retrieval.RetrievalSearchHandler(serverCtx),
			},
		),
	)

	server.AddRoutes(
		rest.WithMiddlewares([]rest.Middleware{authMiddleware},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/subjects/create",
				Handler: subject.SubjectCreateHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/subjects/delete",
				Handler: subject.SubjectDeleteHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/subjects/detail",
				Handler: subject.SubjectDetailHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/subjects/list",
				Handler: subject.SubjectListHandler(serverCtx),
			},
			rest.Route{
				Method:  http.MethodPost,
				Path:    "/api/subjects/update",
				Handler: subject.SubjectUpdateHandler(serverCtx),
			},
		),
	)
}
