// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"enterprise-rag/backend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	_ = server
	_ = serverCtx
}
